version: '3.7'

services:
  postgres:
    image: postgres:13-alpine
    container_name: events-fastAPI-postgres
    volumes:
      - events_fastAPI_pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=events_fastAPI_api
      - POSTGRES_DB=events_fastAPI_api
      - POSTGRES_PASSWORD=pswd1234
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: events_fastAPI-app
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      - postgres
      - redis
      - beat
      - worker
    ports:
      - "8080:8080"
    command: uvicorn --port 8080 --host 0.0.0.0 --loop uvloop --reload main:app

  redis:
    image: redis:7-alpine

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi_events_celery_beat
    command: celery -A main.celery beat -l debug
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi_events_celery_worker
    command: celery -A main.celery worker --loglevel=debug
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

volumes:
  events_fastAPI_pgdata: