"""email_verify

Revision ID: 35be8dc25b0a
Revises: 4399c3fa41c1
Create Date: 2023-07-18 16:38:14.852757

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '35be8dc25b0a'
down_revision = '4399c3fa41c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
