"""add_data_source_table

Revision ID: 3e0da213264c
Revises: ee98ea188fd2
Create Date: 2023-08-07 12:53:08.093706

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '3e0da213264c'
down_revision = 'ee98ea188fd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
