"""

Revision ID: 4399c3fa41c1
Revises: 801cb3d45860
Create Date: 2023-07-18 16:37:16.792110

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4399c3fa41c1'
down_revision = '801cb3d45860'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###
