"""add_data_source_table_v3

Revision ID: 7ee29cdf00c0
Revises: ed8982833557
Create Date: 2023-08-07 14:10:16.172513

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '7ee29cdf00c0'
down_revision = 'ed8982833557'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source', sa.Column('last_event_id', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_source', 'last_event_id')
    # ### end Alembic commands ###
