"""user_add_tfa

Revision ID: e96fbc34c320
Revises: e15a4a065a55
Create Date: 2023-07-27 09:11:29.689212

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e96fbc34c320'
down_revision = 'e15a4a065a55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tfa_secret', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('tfa_enabled', sa.Boolean(), server_default='False', nullable=False))
    op.create_index(op.f('ix_users_tfa_secret'), 'users', ['tfa_secret'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tfa_secret'), table_name='users')
    op.drop_column('users', 'tfa_enabled')
    op.drop_column('users', 'tfa_secret')
    # ### end Alembic commands ###
