"""add_data_source_table_v2

Revision ID: ed8982833557
Revises: 3e0da213264c
Create Date: 2023-08-07 13:05:01.528578

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed8982833557'
down_revision = '3e0da213264c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('handler', sa.String(length=1024), nullable=True),
    sa.Column('api_url', sa.String(length=1024), nullable=True),
    sa.Column('secret', sa.String(length=1024), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_source')
    # ### end Alembic commands ###
