"""email_validate

Revision ID: feb7515fdfd6
Revises: 35be8dc25b0a
Create Date: 2023-07-18 17:03:42.087340

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'feb7515fdfd6'
down_revision = '35be8dc25b0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
